### ISSUE TITLE
Doubt regarding heading angle and box sizes !!

### ISSUE THREAD

**Issue by praj441** [zaiweizhang/H3DNet#12]
@GitBoSun @zaiweizhang 
Hi,
In file sunrgbd/sunrgbd_detection_dataset_hd, it is mentioned in comments that, sizes l,w,h are half the box dimensions and angle is measured from +x to -y.
While, in file utils/show_results_sunrgbd.py, the box sizes l,w,h seems to be taken as equal to the predicted/gt box dimensions.
Please comment on exactly what sizes l,w,h, and the heading angle represent in the input labels and in the predicted labels by the model.

**Comment by GitBoSun** [comment]
Hi,
Sorry for the confusion. In our experiments, we use full size rather than half size.

**Comment by praj441** [comment]
@GitBoSun 
Hi,
Thank you very much for your reply. I am really sorry for the inconvenience again but can you also please comment about the heading angle.
In the file sunrgbd/sunrgbd_detection_dataset_hd (line 17), the comment is as follows:-  "The heading angle is a rotation rad from +X rotating towards -Y. (+X is 0, -Y is pi/2)"

But I think the angle is measured from +X rotating towards +Y. (+X is 0, +Y is pi/2)"

Please comment on which is correct?

**Comment by praj441** [comment]
To all of those having similar doubt like me, my conclusion is as follow:
If you are preparing your custom dataset, then in the labels, the sizes l,w,h should be half of the actual dimensions of the box. And the heading angle should be +X rotating towards -Y. (+X is 0, -Y is pi/2).

**Comment by zaiweizhang** [comment]
Hi praj441,

Sorry for the late reply. I thought the question is still about utils/show_results_sunrgbd.py. Let me assign this question to me.

There is confusion. 
We do use half of the actual dimensions of the box for SUNRGBD, and use the full dimensions for ScanNet. Your conclusion is correct.

Thanks again for your interests in our work. I will definitely try to get back to you quicker next time.
Zaiwei

**Comment by praj441** [comment]
@zaiweizhang 
Thank you very much for confirming!
