### ISSUE TITLE
Performance of a model with single backbone

### ISSUE THREAD

**Issue by chrockey** [zaiweizhang/H3DNet#16]
Hi,

Thank you for sharing this great work!
I have a simple question about the performance with single backbone.
What is the mAP@0.25 and mAP@0.5 on both ScanNet and SUN RGB-D when the model use single backbone?

Regards,

**Comment by zaiweizhang** [comment]
That's a great question! With ScanNet, we have tried with on BB. You should get around 66 mAP@0.25 from scratch. 
For SUN RGB-D, we have not tried. You are welcome to try it with yourself.

With the pretrained model from [here](https://github.com/facebookresearch/DepthContrast), we used a backbone model which is about 3x larger than the original one, we are able to achieve around 69 mAP@0.25 for ScanNet and 63 mAP@0.25 for SUN RGBD.

**Comment by chrockey** [comment]
@zaiweizhang 
Thank you for your kind reply!

**Comment by xuntan97** [comment]
> Hi,
> 
> Thank you for sharing this great work!
> I have a simple question about the performance with single backbone.
> What is the mAP@0.25 and mAP@0.5 on both ScanNet and SUN RGB-D when the model use single backbone?
> 
> Regards,

Hi, i have the same question as you. So i want to know have you test the single backbone. And share the result. Thank you very much!

**Comment by xuntan97** [comment]
@chrockey 
hi, I have the same question as you. So did you test the single backbone. If so, can you share the result. Thank you very much!

**Comment by zaiweizhang** [comment]
@xuntan97 I have personally tried it several times. It was 66 mAP@0.25 from scratch for scannet. And with the pretrained model from [here](https://github.com/facebookresearch/DepthContrast), we used a backbone model which is about 3x larger than the original one, we are able to achieve around 69 mAP@0.25 for ScanNet and 63 mAP@0.25 for SUN RGBD. Hope this helps!

**Comment by xuntan97** [comment]
@zaiweizhang Thank you for your reply. I still have some questions. In your paper, you give the mAP 60.1% on SUNRGBD. which scale does it use?  And what do you think about the args--use_color,  should we set use or not use.

**Comment by zaiweizhang** [comment]
That's using four BB without pretraining from the method described [here](https://github.com/facebookresearch/DepthContrast). You should not set the --use_color, it does not give performance gain and sometimes give worse results.
