### ISSUE TITLE
Can you share with us pretrained model ?

### ISSUE THREAD

**Issue by giangdip2410** [zaiweizhang/H3DNet#17]
Hi,

Have a good day to you. I would like to seek your help for find pretrained model of H3DNet to testing purpose only. 
Thank you very much.

**Comment by zaiweizhang** [comment]
Thank you for interested in our work!

Here is a link to scannet and sunrgbd models with corresponding log file.
https://drive.google.com/file/d/1WGAMrG3cyPkFRHPBdHgwhXfuKFLAQSCh/view?usp=sharing

**Comment by giangdip2410** [comment]
thank you very much for your great work

**Comment by CocoRin5932** [comment]
Hi. 
I would like to use the pretrained model of H3DNet too, but the shared link is no longer available.
Could you share it again, please?

**Comment by 13717630148** [comment]
@CocoRin5932 @giangdip2410 @yanghtr @GitBoSun @zaiweizhang same problem, can you share it again?
