### ISSUE TITLE
Question about data augmentation on ScanNet

### ISSUE THREAD

**Issue by Na-Z** [zaiweizhang/H3DNet#19]
Hi zaiwei,

When performing data augmentation on ScanNet, you also flipped the height. 
https://github.com/zaiweizhang/H3DNet/blob/e89d092bdf4c2ab1df576e6c4ff12bcbc2d55b2e/scannet/scannet_detection_dataset_hd.py#L188
https://github.com/zaiweizhang/H3DNet/blob/e89d092bdf4c2ab1df576e6c4ff12bcbc2d55b2e/scannet/scannet_detection_dataset_hd.py#L195
May I know the reason? As far as I know, the height should not be flipped. 

Additionally,  you set the heading angle as the ```rot_angle``` (since original heading angle is 0 in ScanNet)
https://github.com/zaiweizhang/H3DNet/blob/e89d092bdf4c2ab1df576e6c4ff12bcbc2d55b2e/scannet/scannet_detection_dataset_hd.py#L202
However, the ```rotate_aligned_boxes``` function returns params of axis-aligned bboxes. I  don't understand why you set heading angle to  ```rot_angle``` instead of 0 here. Could you explain?

Thank you.

**Comment by zaiweizhang** [comment]
Hi Na-Z,

meta_vertices[:, 6] = -1 * meta_vertices[:, 6] This line is actually flipping the angle.
And this line: (meta_vertices[:, 6] += rot_angle ) is applying a global rotation so it would not affect individual objects' front orientation prediction.
