### ISSUE TITLE
About ground truth

### ISSUE THREAD

**Issue by windmillknight** [zaiweizhang/H3DNet#2]
Hi~How do you get the ground truth in Figure 10?

**Comment by zaiweizhang** [comment]
Thank you for your interest in our work! To get the ground truth of whether a point is close to a geometric primitive or not (bb face or bb edge), we compute the point's distance to its nearest bb face or bb edge, and say a point lies close to a BB face or a BB edge if that distance is smaller than 0.2m. We described this in Section 3.2 of the paper (beginning of page 7). For implementation details, please look at our data loaders for ScanNet and SUNRGBD.
