### ISSUE TITLE
Train H3DNet on Stanford 3D-Semantics Dataset

### ISSUE THREAD

**Issue by giangdip2410** [zaiweizhang/H3DNet#23]
Hi bro @zaiweizhang ,

I am trying to train H3DNet on Stanford 3D-Semantics Dataset. When I convert Stanford 3D-Semantics Dataset to Scannet V2 format, I face a difficult for "sence_all_noangle_40cls.npy".  Could you please share with me your code for convert to "sence_all_noangle_40cls.npy" ? As I read your code and VoteNet, column 8th at file "all_noangle_40cls.npy" is instance_labels and column 9th is semantic_labels. But I do not know column from 1st to 7th is represent for which data. 

I read from Votenet Code column from 1st to 7th seem is  a box as (cx,cy,cz,dx,dy,dz,semantic_label) but I am not sure because a file "noangle_40cls.npy" has (50k ,9) shape, so I think boxes can not be represent as format like this.

I hope to receive your advice soon. Thank you very much.

**Comment by zaiweizhang** [comment]
@yanghtr Can you take a look at this question?

**Comment by giangdip2410** [comment]
@zaiweizhang : thank you so much.

**Comment by yanghtr** [comment]
The 7th column should be the oriented angle. You can check all the data in scannet and meta_data[:, 6] should all be 0 since we do not consider bounding box angle in scannet.

**Comment by giangdip2410** [comment]
@yanghtr : thank you for you reply.
