### ISSUE TITLE
Error when train on sunrgbd

### ISSUE THREAD

**Issue by SnowPi** [zaiweizhang/H3DNet#25]
![image](https://user-images.githubusercontent.com/25281085/156915220-42c42fc4-ec9f-43ec-ab10-5ac0ac116eaf.png)

i'm confused about that

**Comment by zaiweizhang** [comment]
I believe this is just a comment error. @yanghtr

**Comment by SnowPi** [comment]
When using the data you provided, there is no problem. If you're using a different data processing approach with VoteNet's, it's better to point it out. thanks.

**Comment by yanghtr** [comment]
Sorry the comment might be wrong (legacy). You can load the data to check it.
