### ISSUE TITLE
Problems for pre-processed data

### ISSUE THREAD

**Issue by mutianxu** [zaiweizhang/H3DNet#28]
Dear author,

Thanks for your great work!

I have two problems about your pre-processed data.

1. As indicated in your readme, the pre-processing procedure is same with votenet. However, after processed by votenet code, there will be no _all_noangle_40cls.npy for producing the meta_vertice in your [code here](https://github.com/zaiweizhang/H3DNet/blob/master/scannet/scannet_detection_dataset_hd.py#L136).

2. When I tried to download your processed data, the link you provide shows "file does not exist".

Could you please help with this two questions?

Thanks a lot!

**Comment by zaiweizhang** [comment]
1. We use similar pre-processing procedure but we do need extra codes to find the surface and line points. 
2. The data link has been updated. 

Please take a look now.
