### ISSUE TITLE
About the PRED_PATH in show_results_sunrgbd.py

### ISSUE THREAD

**Issue by MezereonXP** [zaiweizhang/H3DNet#8]
Hi zaiweizhang,

When I am trying to make visualization on the result of a checkpoint, I found that the PRED_PATH in show_results_sunrgbd.py is confused. After I execute the eval.py, there is no record of predictions.

Could you please give me some advices to set the PRED_PATH or construct the prediction files?

Thanks,
Ke

**Comment by GitBoSun** [comment]
Hi Ke,
Thanks for your interest in our paper! 
When you run the eval.py, you will specify the `--dump_dir`, which is the folder containing predicted results. The files in that folder will be like `'center'+scan_name+'_nms.npy'`. Set the PRED_PATH to this folder and you will load and visualize the predictions.
Sorry for the confusion. If you have further questions, please let me know!
Best,
Bo

**Comment by MezereonXP** [comment]
Thanks for your reply.

My shell likes:
```
python eval.py --data_path /data/gaohan/SUN-RGB-D/sunrgbd --dataset sunrgbd --model hdnet --checkpoint_path log_sunrgbd/checkpoint.tar --dump_dir eval_sunrgbd --cluster_sampling seed_fps --use_3d_nms --use_cls_nms --per_class_proposal
```

But after I execute the shell and specify the ```--dump_dir```, there is only a txt file named ```log_eval.txt``` in the dump dir.

**Comment by MezereonXP** [comment]
I just found the function ```log_string``` which can write the string into the log file in eval.py.
But I could not find any other functions which save the prediction to the dump dir.

**Comment by GitBoSun** [comment]
Hi, sorry for the confusion. We forgot to add dump_results to eval.py. We've updated it. Btw, you can use the dump_results function normally in train.py.
