### ISSUE TITLE
Results on ScanNet

### ISSUE THREAD

**Issue by raoyongming** [zaiweizhang/H3DNet#9]
Hi, thanks for sharing your code. 

I am trying to reproduce the results on ScanNet using the default configs. But I can only obtain around 64-65 mAP@0.25, which is lower than the results in your paper (67.2). Do you have any advice to reproduce your results?

Here are the training logs [log_train.txt](https://github.com/zaiweizhang/H3DNet/files/5432522/log_train.txt) [log_train_run2.txt](https://github.com/zaiweizhang/H3DNet/files/5432524/log_train_run2.txt)

**Comment by zaiweizhang** [comment]
I briefly looked at your log files. I do think that the performance is different. 
Here are two log files from our experiments. 
[log_train.txt](https://github.com/zaiweizhang/H3DNet/files/5433817/log_train.txt)
[log_train_2.txt](https://github.com/zaiweizhang/H3DNet/files/5433818/log_train_2.txt)

Would you mind sharing your pytorch, conda, and cudnn version?

**Comment by raoyongming** [comment]
Thanks for your quick reply. My experiments were conducted using 4 1080ti gpus with pytorch 1.6.0, cuda 10.2 and cudnn 7.6.5

**Comment by zaiweizhang** [comment]
Since we are using Votenet's codebase, most of our experiments are conducted with pytorch 1.1.0. cuda 10.0, and cudnn 7.6
I have also tried with pytorch version 1.2.0, and cuda 10.1. The results are similar. 

I would suggest you try our code with this setting: pytorch 1.1.0. cuda 10.0, and cudnn 7.6.

**Comment by raoyongming** [comment]
I tried using pytorch 1.1.0 and 3 gpus (bs=9) to conduct the experiments and obtained 67-68 mAP@0.25 (slightly better than the results in your paper). Maybe it is because batch size = 2 on each gpu is too small for BN. Thanks for your help!
